### ISSUE TITLE
Apartado Conclusiones y Líneas de trabajo futuras del desarrollo del proyecto

### ISSUE THREAD

**Issue by EduardoRisco** [EduardoRisco/GESPRO_GESTIONTAREAS#3]

**Comment by EduardoRisco** [comment]
El cliente no está de acuerdo con el prototipo de la interface, hay que hacerla mas intuitiva

**Comment by MatiasMurro** [comment]
Adjunto nuevo prototipo de la interface.

**Comment by MatiasMurro** [comment]
Adjunto nuevo prototipo de la interface.

**Comment by MatiasMurro** [comment]
Adjunto nuevo prototipo de la interface.

**Comment by EduardoRisco** [comment]
El esquema del formulario está correcto, quedaría mejorar las metáforas

**Comment by EduardoRisco** [comment]
El esquema del formulario está correcto, quedaría mejorar las metáforas

**Comment by EduardoRisco** [comment]
Crear la documentación correspondiente al apartado Conclusiones y Líneas de trabajo futuras del proyecto.

**Comment by MatiasMurro** [comment]
Enviado los aspectos relevantes del desarrollo modificados.

**Comment by EduardoRisco** [comment]
Revisado, ok
