### ISSUE TITLE
Apéndice B: Especificación de Requisitos

### ISSUE THREAD

**Issue by MatiasMurro** [EduardoRisco/GESPRO_GESTIONTAREAS#4]

**Comment by EduardoRisco** [comment]
Adjunto el código de los test de los códigos 1 y 2. Hay que revisar el 2 aparece este error
-____________________

**Comment by MatiasMurro** [comment]
Lo he revisado y se encuentra en el commits 13.

**Comment by EduardoRisco** [comment]
Sigue sin funcionar

**Comment by clopezno** [comment]
Estimados Eduardo y Matías
Me están llegando notificaciones de vuestro proyecto de Github y os quiero aclarar un par de cuestiones que espero que os ayuden a comprender mejor la práctica.

Las tarea/historias de usuario que tenéis que describir en vuestro trabajo están [aquí](https://bitbucket.org/ppp0015/tfg-gii-revisiones-autom-ticas-de-calidad-de-proyectos-con/issues). No hay que inventar ninguna nueva.



Saludos
Carlos López

**Comment by EduardoRisco** [comment]
Crear la documentación correspondiente al apéndice Especificación de Requisitos

**Comment by EduardoRisco** [comment]
Los requisitos están descritos, adjunto archivo

**Comment by MatiasMurro** [comment]
Esta ok.
