### ISSUE TITLE
Apéndice A: Plan de proyecto 

### ISSUE THREAD

**Issue by MatiasMurro** [EduardoRisco/GESPRO_GESTIONTAREAS#5]

**Comment by EduardoRisco** [comment]
Falta revisar la BBDD antes de cargarla

**Comment by EduardoRisco** [comment]
Crear la documentación correspondiente al apéndice Plan de Proyecto

**Comment by MatiasMurro** [comment]
He subido la ultima documentación.

**Comment by EduardoRisco** [comment]
ok , está revisado
